/* COPYRIGHT (C) HARRY CLARK 2024 */

/* LAMBDA EXPRESSION TEST */

/* THIS FILE PERTAINS TOWARDS THE USAGE OF WRITING A SIMPLE LAMBDA EXPRESSION IN C */
/* FOR THE PURPOSES OF DEMONSTRATING CHARACTERISTICS BETWEEN HEAP AND STACK ALLOCATION IN LANGUAGES */

#include <stdio.h>
#include <stdlib.h>

void* PRINT_ARRAY_ELEMENTS(int VALUE)
{
    printf("%d\n", VALUE);
}

int main(int argc, char* argv[])
{
    int NUMS[] = {2, 3, 7, 14, 23};
    int INDEX;

    /* ALLOCATE MEMORY ON THE STACK FOR THESE METHODS  */
    /* THIS IS BY CASTING AN ARBITARY SIZE OF THE RELEVANT DATA STRUCTURE */

    /* SUCH IS THE CASE WITH ARRAYS, THEIR SIZE IS INDISTINGUISHABLE */
    /* THEREFORE, WE CAST A UINT TO ACCOMMODATE */

    int NUM_SIZE = (unsigned int)sizeof(NUMS) / sizeof(NUMS[0]);

    /* ASSUME HOW MANY RESPECTIVE ELEMENTS THERE ARE BASED ON THE OFFSET */
    /* PRINT THEM OUT BASED ON THE INDEX OF HOW MANY ELEMENTS ARE THERE */

    for (INDEX = 0; INDEX < NUM_SIZE; INDEX++)
    {
        PRINT_ARRAY_ELEMENTS(NUMS[INDEX]);
    }

    return 0;
}